# 1. 定义

In [1]:
import numpy as np

In [10]:
array = np.array([1,2,3], dtype=np.int32)
print(array)
print("shape of array: {}".format(array.shape))#矩阵的形状
print("ndim of array: {}".format(array.ndim))#矩阵的维度
print("size of array: {}".format(array.size))

[1 2 3]
shape of array: (3,)
ndim of array: 1
size of array: 3


In [11]:
#列表转为numpy矩阵
array = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float32)
print(array)
print(type(array))
print(array.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
float32


In [12]:
array = np.array([
    [1,2,3],
    [4,5,6]
])
print("shape of array: {}".format(array.shape))#矩阵的形状
print("ndim of array: {}".format(array.ndim))#矩阵的维度
print("size of array: {}".format(array.size))

shape of array: (2, 3)
ndim of array: 2
size of array: 6


In [13]:
#生成全0矩阵
zeros_array = np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#生成全1数据
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#生成连续数据
array = np.arange(1,12,2)#生层1-10步长为2的数据
print(array)

[ 1  3  5  7  9 11]


In [18]:
array = array.reshape(2,3)
print(array)

[[ 1  3  5]
 [ 7  9 11]]


In [20]:
#当然也可以生成一些随机数据
np.random.seed(42)
array = np.random.normal(size=(2,3))
print(array)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]


# 2. 运算

In [21]:
import numpy as np

In [25]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,b)

[1 2 3 4] [5 6 7 8]


In [26]:
print(a-b)

[-4 -4 -4 -4]


In [27]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [29]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.arange(6).reshape((2,3))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]]


In [31]:
print(np.dot(a,b.T))

[[ 8 26]
 [17 62]]


In [32]:
print(np.sum(a))

21


In [33]:
#numpy中用axis表示维度
# axis=0代表列
# axis=1代表行
print(np.sum(a, axis=0))

[5 7 9]


In [34]:
print(np.sum(a, axis=1))

[ 6 15]


In [35]:
print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))

6
[4 5 6]
[3 6]


In [40]:
a = np.array([
    [2,5,1],
    [0,6,8]
])

In [42]:
# 查找当前矩阵中最小元素的下标
print(np.argmin(a))
print(np.argmin(a, axis=0))
print(np.argmin(a, axis=1))

3
[1 0 0]
[2 0]
