# 1. 定义

In [1]:
import numpy as np

In [10]:
array = np.array([1,2,3], dtype=np.int32)
print(array)
print("shape of array: {}".format(array.shape))#矩阵的形状
print("ndim of array: {}".format(array.ndim))#矩阵的维度
print("size of array: {}".format(array.size))

[1 2 3]
shape of array: (3,)
ndim of array: 1
size of array: 3


In [11]:
#列表转为numpy矩阵
array = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float32)
print(array)
print(type(array))
print(array.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>
float32


In [12]:
array = np.array([
    [1,2,3],
    [4,5,6]
])
print("shape of array: {}".format(array.shape))#矩阵的形状
print("ndim of array: {}".format(array.ndim))#矩阵的维度
print("size of array: {}".format(array.size))

shape of array: (2, 3)
ndim of array: 2
size of array: 6


In [13]:
#生成全0矩阵
zeros_array = np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#生成全1数据
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#生成连续数据
array = np.arange(1,12,2)#生层1-10步长为2的数据
print(array)

[ 1  3  5  7  9 11]


In [18]:
array = array.reshape(2,3)
print(array)

[[ 1  3  5]
 [ 7  9 11]]


In [20]:
#当然也可以生成一些随机数据
np.random.seed(42)
array = np.random.normal(size=(2,3))
print(array)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]


In [ ]:
array = array.astype(np.float64)

# 2. 运算

In [21]:
import numpy as np

In [25]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,b)

[1 2 3 4] [5 6 7 8]


In [26]:
print(a-b)

[-4 -4 -4 -4]


In [27]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [29]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.arange(6).reshape((2,3))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]]


In [31]:
print(np.dot(a,b.T))

[[ 8 26]
 [17 62]]


In [32]:
print(np.sum(a))

21


In [33]:
#numpy中用axis表示维度
# axis=0代表列
# axis=1代表行
print(np.sum(a, axis=0))

[5 7 9]


In [34]:
print(np.sum(a, axis=1))

[ 6 15]


In [35]:
print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))

6
[4 5 6]
[3 6]


In [40]:
a = np.array([
    [2,5,1],
    [0,6,8]
])

In [42]:
# 查找当前矩阵中最小元素的下标
print(np.argmin(a))
print(np.argmin(a, axis=0))
print(np.argmin(a, axis=1))

3
[1 0 0]
[2 0]


In [44]:
print("mean : {}".format(np.mean(a))) # 求矩阵均值

mean : 3.6666666666666665


In [45]:
print("mean : {}".format(np.mean(a, axis=0)))

mean : [1.  5.5 4.5]


In [46]:
print(np.median(a))# 求矩阵中数据的中位数

3.5


# 3. 获取数据

In [47]:
import numpy as np

In [48]:
a = np.arange(1,7)
b = a.reshape((2,3))
print(a)
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [49]:
a[3]

4

In [50]:
b[0]

array([1, 2, 3])

In [51]:
b[0][1]

2

In [52]:
a[0:3]

array([1, 2, 3])

In [53]:
b[1,0:2]

array([4, 5])

# 4. 数组合并

In [1]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])

In [2]:
c = np.vstack((a,b))
print(c)

[[1 1 1]
 [2 2 2]]


In [3]:
d = np.hstack((a,b))
print(d)

[1 1 1 2 2 2]


In [4]:
C = np.concatenate((a,b,a), axis = 0)
print(C)

[1 1 1 2 2 2 1 1 1]


In [6]:
D = np.concatenate(([a],[b],[a]), axis = 1)
print(D)

[[1 1 1 2 2 2 1 1 1]]


In [7]:
a = np.arange(8).reshape(2,4)
b = np.arange(8).reshape(2,4)

In [8]:
c = np.concatenate((a,b), axis=0)
print(c)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


In [10]:
d = np.concatenate((a,b), axis=1)
print(d)

[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


In [11]:
a = np.array([1,2,3])
print(a)
a = a[:, np.newaxis]
print(a)

[1 2 3]
[[1]
 [2]
 [3]]


# 5. 矩阵分割

In [12]:
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
print(np.split(a, 2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [15]:
print(np.split(a, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


# 6. 矩阵复制

In [16]:
import numpy as np
a = np.arange(4)
print(a)

[0 1 2 3]


In [17]:
#当使用=时相当于多个指针指向同一变量
b = a
b[0] = 12
print(a)

[12  1  2  3]


In [18]:
#使用copy函数则会开辟一块新的空间，将原数据复制一份
c = a.copy()
print(c)

[12  1  2  3]


In [19]:
c[0] = 11
print(c)
print(a)

[11  1  2  3]
[12  1  2  3]


# 7. 广播

In [23]:
#numpy中最为重要的就是广播机制，当两个矩阵维度不同时仍然可以进行运算操作
a = np.arange(12).reshape((3,4))
b = np.array([1,2,3,4])
print("a = ", a)
print("b = ", b)

a =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b =  [1 2 3 4]


In [24]:
print(a+b)#此时numpy会自动将b与a中的每行分别相加

[[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]]
